project:
  type: website

website:
  title: "Ailys' IS415 Journey"
  navbar:
    left: 
      - href: index.qmd
        text: Home
      - about.qmd
      - text: "Hands-On Exercises"
        menu: 
          - text: "Hands-on Exercise 1"
            href: "Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01.html"
      - text: "In-class Exercises"
        menu: 
          - text: "In-class Exercise 2"
            href: "In-class_Ex/In-class_Ex02/In-class_Ex02.html"
format:
  html:
    theme: lumen
    css: styles.css
    toc: true

editor: visual

